import Head from "next/head";
import Title from "./Title";
import SEO from "./SEO";
import Bots from "./Bots";
import Structure from "./Structure";
import Strategy from "./Strategy";
import Solution from "./Solution";
import Lighthouse from "./Lighthouse";
import Conclusion from "./Conclusion";
import Footer from "./Footer";

export default function Home() {
  return (
    <div className="full" id="full">
      <Head>
        <title>Search Engine Optimization</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="../favicon_io/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="../favicon_io/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="../favicon_io/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="../favicon_io/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <div className="body">
        <Title />
        <SEO />
        <Bots />
        <Structure />
        <Strategy />
        <Solution />
        <Lighthouse />
        <Conclusion />
      </div>
      <Footer />
    </div>
  );
}
